package pe.gob.mlvictoria.fiscalizacioncontrol.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.mapping.StatementType;
import pe.gob.mlvictoria.fiscalizacioncontrol.dto.registrarcontribuyente.ContribuyenteRequest;
import pe.gob.mlvictoria.fiscalizacioncontrol.dto.registrarcontribuyente.ContribuyenteResponse;

@Mapper
public interface RegContribuyenteMapper {
    @Select("""
            EXEC Rentas.sp_Mcontribuyente
              @busc = #{dto.busc, mode=IN, jdbcType=INTEGER},
              @codigo = #{dto.codigo, mode=IN, jdbcType=VARCHAR},
              @id_pers = #{dto.idPers, mode=IN, jdbcType=CHAR},
              @id_docu = #{dto.idDocu, mode=IN, jdbcType=CHAR},
              @num_doc = #{dto.numDoc, mode=IN, jdbcType=VARCHAR},
              @nombres = #{dto.nombres, mode=IN, jdbcType=VARCHAR},
              @paterno = #{dto.paterno, mode=IN, jdbcType=VARCHAR},
              @materno = #{dto.materno, mode=IN, jdbcType=VARCHAR},
              @id_dist = #{dto.idDist, mode=IN, jdbcType=VARCHAR},
              @tipourb = #{dto.tipourb, mode=IN, jdbcType=VARCHAR},
              @des_urb = #{dto.desUrb, mode=IN, jdbcType=VARCHAR},
              @tipovia = #{dto.tipovia, mode=IN, jdbcType=CHAR},
              @des_via = #{dto.desVia, mode=IN, jdbcType=VARCHAR},
              @id_zona = #{dto.idZona, mode=IN, jdbcType=VARCHAR},
              @id_urba = #{dto.idUrba, mode=IN, jdbcType=VARCHAR},
              @id_via = #{dto.idVia, mode=IN, jdbcType=VARCHAR},
              @referencia = #{dto.referencia, mode=IN, jdbcType=VARCHAR},
              @manzana = #{dto.manzana, mode=IN, jdbcType=CHAR},
              @lote = #{dto.lote, mode=IN, jdbcType=VARCHAR},
              @sub_lote = #{dto.subLote, mode=IN, jdbcType=VARCHAR},
              @numero = #{dto.numero, mode=IN, jdbcType=VARCHAR},
              @departam = #{dto.departam, mode=IN, jdbcType=VARCHAR},
              @nestado = #{dto.nestado, mode=IN, jdbcType=INTEGER},
              @operador = #{dto.operador, mode=IN, jdbcType=VARCHAR},
              @estacion = #{dto.estacion, mode=IN, jdbcType=VARCHAR},
              @fech_ing = #{dto.fechIng, mode=IN, jdbcType=TIMESTAMP},
              @id_tipocontri = #{dto.idTipocontri, mode=IN, jdbcType=VARCHAR},
              @id_subtipocontri = #{dto.idSubtipocontri, mode=IN, jdbcType=VARCHAR},
              @id_motivo_actualizacion = #{dto.idMotivoActualizacion, mode=IN, jdbcType=VARCHAR},
              @tipo_interior_id = #{dto.tipoInteriorId, mode=IN, jdbcType=VARCHAR},
              @tipo_agrupamiento_id = #{dto.tipoAgrupamientoId, mode=IN, jdbcType=VARCHAR},
              @tipo_ingreso_id = #{dto.tipoIngresoId, mode=IN, jdbcType=VARCHAR},
              @tipo_edificio_id = #{dto.tipoEdificioId, mode=IN, jdbcType=VARCHAR},
              @tipo_busqueda = #{dto.tipoBusqueda, mode=IN, jdbcType=CHAR},
              @razon = #{dto.razon, mode=IN, jdbcType=VARCHAR},
              @nomvia = #{dto.nomvia, mode=IN, jdbcType=VARCHAR},
              @letra1 = #{dto.letra1, mode=IN, jdbcType=VARCHAR},
              @numero2 = #{dto.numero2, mode=IN, jdbcType=VARCHAR},
              @piso = #{dto.piso, mode=IN, jdbcType=VARCHAR},
              @letra2 = #{dto.letra2, mode=IN, jdbcType=VARCHAR},
              @nombre_ingreso = #{dto.nombreIngreso, mode=IN, jdbcType=VARCHAR},
              @nombre_agrupamiento = #{dto.nombreAgrupamiento, mode=IN, jdbcType=VARCHAR},
              @nombre_edificio = #{dto.nombreEdificio, mode=IN, jdbcType=VARCHAR},
              @numero_interno = #{dto.numeroInterno, mode=IN, jdbcType=VARCHAR},
              @letra_interno = #{dto.letraInterno, mode=IN, jdbcType=VARCHAR},
              @anno = #{dto.anno, mode=IN, jdbcType=VARCHAR},
              @nro = #{dto.nro, mode=IN, jdbcType=VARCHAR},
              @dpto = #{dto.dpto, mode=IN, jdbcType=VARCHAR},
              @Mza = #{dto.Mza, mode=IN, jdbcType=VARCHAR},
              @Lte = #{dto.Lte, mode=IN, jdbcType=VARCHAR},
              @SubLte = #{dto.SubLte, mode=IN, jdbcType=VARCHAR},
              @correo_e = #{dto.correo_e, mode=IN, jdbcType=VARCHAR},
              @telefono1 = #{dto.telefono1, mode=IN, jdbcType=VARCHAR},
              @anexo1 = #{dto.anexo1, mode=IN, jdbcType=VARCHAR},
              @telefono2 = #{dto.telefono2, mode=IN, jdbcType=VARCHAR},
              @anexo2 = #{dto.anexo2, mode=IN, jdbcType=VARCHAR},
              @partida_defuncion = #{dto.partidaDefuncion, mode=IN, jdbcType=VARCHAR},
              @fecha_defuncion = #{dto.fechaDefuncion, mode=IN, jdbcType=DATE},
              @flag_notificar = #{dto.flagNotificar, mode=IN, jdbcType=CHAR},
              @num_doc_coac = #{dto.numDocCoac, mode=IN, jdbcType=CHAR},
              @tipo_doc_coac = #{dto.tipodocCoac, mode=IN, jdbcType=CHAR},
              @cbzonas = #{dto.cbzonas, mode=IN, jdbcType=VARCHAR},
              @flag_valida_PIDE = #{dto.flagValidaPide, mode=IN, jdbcType=INTEGER},
              @tipo_modificacion = #{dto.tipoModificacion, mode=IN, jdbcType=INTEGER},
              @tipo_operacion = #{dto.tipoOperacion, mode=IN, jdbcType=INTEGER},
              @sexo = #{dto.sexo, mode=IN, jdbcType=VARCHAR},
              @pag_web = #{dto.pagWeb, mode=IN, jdbcType=VARCHAR},
              @estado_civil = #{dto.estadoCivil, mode=IN, jdbcType=INTEGER},
              @fech_nacimiento = #{dto.fechNacimiento, mode=IN, jdbcType=DATE},
              @autoriza_gsat = #{dto.autorizaGsat, mode=IN, jdbcType=INTEGER},
              @sumi_luz = #{dto.sumiLuz, mode=IN, jdbcType=VARCHAR},
              @sumi_agua = #{dto.sumiAgua, mode=IN, jdbcType=VARCHAR},
              @envio_sms = #{dto.envioSms, mode=IN, jdbcType=INTEGER},
              @envio_correo = #{dto.envioCorreo, mode=IN, jdbcType=INTEGER},
              @block = #{dto.block, mode=IN, jdbcType=VARCHAR},
              @interior = #{dto.interior, mode=IN, jdbcType=VARCHAR},
              @tienda = #{dto.tienda, mode=IN, jdbcType=VARCHAR},
              @stand = #{dto.stand, mode=IN, jdbcType=VARCHAR},
              @oficina = #{dto.oficina, mode=IN, jdbcType=VARCHAR},
              @sub_mz = #{dto.subMz, mode=IN, jdbcType=VARCHAR},
              @sotano = #{dto.sotano, mode=IN, jdbcType=VARCHAR},
              @mezzan = #{dto.mezzan, mode=IN, jdbcType=VARCHAR},
              @seccion = #{dto.seccion, mode=IN, jdbcType=VARCHAR},
              @unidad_inmobiliaria = #{dto.unidadInmobiliaria, mode=IN, jdbcType=VARCHAR},
              @etapa = #{dto.etapa, mode=IN, jdbcType=VARCHAR},
              @sector = #{dto.sector, mode=IN, jdbcType=VARCHAR},
              @puesto = #{dto.puesto, mode=IN, jdbcType=VARCHAR},
              @local_comercial = #{dto.localComercial, mode=IN, jdbcType=VARCHAR},
              @usuario = #{dto.usuario, mode=IN, jdbcType=VARCHAR};
        """)
    @Options(statementType = StatementType.CALLABLE)
    ContribuyenteResponse RegistrarContribuyente(@Param("dto") ContribuyenteRequest request);
}
